'use client';

import React, { useState } from 'react';
import { X, Download, Copy, Check, Printer, FileText, ShieldCheck, Compass } from 'lucide-react';
import { ReconstructionResult } from '@/lib/types';

interface DossierExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: ReconstructionResult | null;
  query: string;
  onCopySuccess: () => void;
}

export default function DossierExportModal({
  isOpen,
  onClose,
  result,
  query,
  onCopySuccess,
}: DossierExportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !result) return null;

  const generateMarkdownReport = (): string => {
    const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);
    
    let md = `# EXECUTIVE FORENSIC DOSSIER
**Generated By**: ReTrace — Lost Context Recovery Engine  
**Date**: ${timestamp} UTC  
**Target Inquiry**: "${query}"  
**Confidence Rating**: ${result.confidence_score.toUpperCase()} (${result.confidence_rationale})

---

## 1. Executive Direct Answer
${result.direct_answer}

---

## 2. Forensic Reasoning & Analysis
${result.reasoning_summary}

---

## 3. Critical Knowledge Blindspots & Missing Context
${
  result.missing_context && result.missing_context.length > 0
    ? result.missing_context
        .map(
          (gap, i) =>
            `### Gap ${i + 1}: ${gap.description} [Category: ${gap.category}]
- **Organizational Impact**: ${gap.impact}
- **Recommended Recovery Action**: ${gap.suggested_investigation}`
        )
        .join('\n\n')
    : 'No critical unrecorded rationale detected.'
}

---

## 4. Reconstructed Chronological Milestones
${
  result.timeline && result.timeline.length > 0
    ? result.timeline
        .map(
          (event) =>
            `- **${event.date}**: ${event.title}
  ${event.description}
  ${event.decision ? `*Decision Registered: ${event.decision}*` : ''}
  ${event.actors?.length ? `*Key Actors: ${event.actors.join(', ')}*` : ''}`
        )
        .join('\n\n')
    : 'No milestones recorded.'
}

---

## 5. Primary Verified Evidence & Citations
${
  result.citations && result.citations.length > 0
    ? result.citations
        .map(
          (c, i) =>
            `${i + 1}. **[${c.source_type.toUpperCase()}] ${c.document_title}**
   > "${c.quote}"
   *(Relevance: ${c.relevance})*`
        )
        .join('\n\n')
    : 'No explicit citations available.'
}

---
*Classification: Confidential // Internal Engineering Intelligence*
`;
    return md;
  };

  const markdownContent = generateMarkdownReport();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    onCopySuccess();
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `retrace-dossier-${Date.now()}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
      <div className="w-full max-w-3xl bg-[#0F1623] border border-[#202E48] rounded-xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh] corner-ticks">
        
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-[#202E48] bg-[#141C2D]/80">
          <div className="flex items-center space-x-2.5">
            <div className="p-1.5 rounded bg-amber-500/10 border border-amber-500/30 text-amber-400">
              <FileText className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-xs font-mono font-bold text-white uppercase tracking-wider">
                EXECUTIVE FORENSIC DOSSIER // EXPORT STUDIO
              </h3>
              <p className="text-[11px] font-mono text-slate-400">
                COMPILED DECISION SUMMARY FOR STAKEHOLDERS & AUDIT TEAMS
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1 rounded-lg transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Content Preview */}
        <div className="p-5 overflow-y-auto flex-1 font-mono text-xs text-slate-300 space-y-4 bg-[#0A0E17]">
          <div className="p-4 rounded-lg bg-[#101623] border border-[#202E48] whitespace-pre-wrap leading-relaxed select-all">
            {markdownContent}
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 border-t border-[#202E48] bg-[#141C2D] flex items-center justify-between">
          <div className="text-[11px] font-mono text-slate-400 flex items-center space-x-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-400" />
            <span>Format: Standard Markdown (.md)</span>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="px-3 py-1.5 text-xs font-mono text-slate-300 hover:text-white bg-[#1A2333] hover:bg-[#223046] border border-[#2A3C5B] rounded-md flex items-center space-x-1.5 transition-all"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={handleCopy}
              className="px-3 py-1.5 text-xs font-mono text-amber-300 bg-amber-500/10 hover:bg-amber-500/20 border border-amber-500/30 rounded-md flex items-center space-x-1.5 transition-all"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied to Clipboard' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handleDownload}
              className="px-4 py-1.5 text-xs font-mono font-semibold text-slate-950 bg-amber-400 hover:bg-amber-300 rounded-md flex items-center space-x-1.5 transition-all shadow-md"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download .MD</span>
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}
